import Head from 'next/head'
import Button from '../components/basic/Button'
import TextInput from '../components/basic/TextInput'
import SelectInput from '../components/basic/SelectInput'
import { timeIntervals } from '../constants'
import Checkbox from '../components/basic/Checkbox'
import ForItem from '../components/basic/ForItem'
import SpecItem from '../components/basic/SpecItem'
import ProductCard from '../components/ProductCard'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TextInput type="password" name="password" labelText="Пароль" />
      <TextInput type="tel" name="tel" labelText="Номер телефона" />

      <SelectInput
        options={timeIntervals}
        name="time"
        labelText="Время получения"
      />
      <br />
      <br />
      <ForItem variant={0} />
      <br />
      <ForItem variant={1} />
      <br />
      <SpecItem variant="m-primary" type="Ценность" data="1400 ккал." />
      <SpecItem variant="m-secondary" type="Жиры" data="5,7 г." />
      <br />
      <SpecItem variant="m-secondary" type="Углеводы" data="5,7 г." />
      <SpecItem variant="m-secondary" type="Белки" data="5,7 г." />

      <br />
      <SpecItem variant="s-primary" type="Жиры" data="5,7 г." />
      <SpecItem variant="s-primary" type="Углеводы" data="5,7 г." />
      <SpecItem variant="s-primary" type="Белки" data="5,7 г." />
      <br />
      <SpecItem variant="l-primary" data="1400 ккал" />
      <SpecItem variant="l-secondary" data="8 дней" />
      <br />
      <br />
      <ProductCard />

      <br />
      <br />
      <br />
      <br />
    </div>
  )
}
