name: lint

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: es and style lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn

      - name: Stylelint
        run: yarn lint:css

      - name: ESlint
        run: yarn lint:js
